// Expo app config (CNG: `ios/` and `android/` are generated by `expo prebuild`, never committed).
// Static values live here so comments are possible; `eas init` (human step) adds the EAS
// project id under `extra.eas.projectId` — read from EXPO_PUBLIC_EAS_PROJECT_ID until then.
import type { ExpoConfig } from 'expo/config';

const easProjectId = process.env.EXPO_PUBLIC_EAS_PROJECT_ID;

const config: ExpoConfig = {
  name: 'AI Stylist',
  slug: 'ai-stylist',
  version: '0.1.0',
  scheme: 'aistylist',
  orientation: 'portrait',
  // No `userInterfaceStyle`: dark mode needs expo-system-ui (native module); theming lands later.
  // New Architecture: always on since SDK 55 (planning/05 §2.2); SDK 57 removed the
  // `newArchEnabled` key from ExpoConfig entirely, so there is nothing to set.
  // Mobile-only for now; web is not a target (planning/05 §2).
  platforms: ['ios', 'android'],
  ios: {
    supportsTablet: false,
    // Placeholder bundle id until the Apple developer account exists (P02 §3, human-only).
    bundleIdentifier: 'app.aistylist.mobile',
  },
  android: {
    // Placeholder application id; must match the Play console entry once created (P02 §3).
    package: 'app.aistylist.mobile',
    adaptiveIcon: {
      backgroundColor: '#111111',
      foregroundImage: './assets/adaptive-icon.png',
    },
    predictiveBackGestureEnabled: false,
  },
  icon: './assets/icon.png',
  // Routes live in src/app (a supported default; no `root` plugin option needed).
  plugins: ['expo-router'],
  // EAS Update runtime = app version: every native change bumps `version`, OTA stays legal (15 §10).
  runtimeVersion: { policy: 'appVersion' },
  experiments: { typedRoutes: true },
  extra: easProjectId ? { eas: { projectId: easProjectId } } : {},
};

export default config;
