// shared-kernel registries -> TypeScript `as const` data (packages/shared-kernel/src/gen/*.ts).
// The hand-written src/{reason-codes,entitlements,units}.ts keep the types, `satisfies` checks and
// helpers and import this data, so the public API of @ai-stylist/shared-kernel is unchanged.
import { docText, src, tsStr, upperSnake } from './naming.mjs';

const banner = (name) =>
  [
    '// GENERATED by tools/codegen/gen-kernel.mjs. DO NOT EDIT: edit the registry and run `just generate`.',
    `// Source: ${src(name)}`,
    '',
  ].join('\n');

const tsArray = (items, notes = []) =>
  [
    '[',
    ...items.map((v, i) => `  ${tsStr(v)},${notes[i] ? ` // ${docText(notes[i])}` : ''}`),
    ']',
  ].join('\n');

const tsObject = (obj, indent = '') => {
  const inner = `${indent}  `;
  const lines = Object.entries(obj).map(([k, v]) => {
    let value;
    if (typeof v === 'string') value = tsStr(v);
    else if (typeof v === 'number') value = String(v);
    else if (Array.isArray(v)) value = `[${v.map(tsStr).join(', ')}]`;
    else value = tsObject(v, inner);
    const key = /^[A-Za-z_$][\w$]*$/.test(k) ? k : tsStr(k);
    return `${inner}${key}: ${value},`;
  });
  return ['{', ...lines, `${indent}}`].join('\n');
};

export function emitTs(reg) {
  const rc = reg['reason-codes'];
  const ent = reg.entitlements;
  const units = reg.units;
  const out = {};

  out['reason-codes.ts'] = [
    banner('reason-codes'),
    `export const REASON_CODE_NAMESPACES = ${tsArray(
      rc.namespaces.map((n) => n.name),
      rc.namespaces.map((n) => n.note),
    )} as const;`,
    '',
    `export const REASON_CODE_STAGES = ${tsArray(rc.stages)} as const;`,
    '',
    `export const REASON_CODES = ${tsObject(rc.codes)} as const;`,
    '',
  ].join('\n');

  out['entitlements.ts'] = [
    banner('entitlements'),
    `export const ENTITLEMENT_VALUE_KINDS = ${tsArray(ent.kinds)} as const;`,
    '',
    `export const ENTITLEMENTS = ${tsObject(ent.entitlements)} as const;`,
    '',
    `export const CREDIT_METERS = ${tsArray(ent.creditMeters)} as const;`,
    '',
  ].join('\n');

  const canonical = Object.fromEntries(
    Object.entries(units.dimensions).map(([d, def]) => [d, def.canonical]),
  );
  out['units.ts'] = [
    banner('units'),
    ...Object.entries(units.dimensions).flatMap(([d, def]) => [
      `export const ${upperSnake(d)}_UNITS = ${tsArray(def.units)} as const;`,
      '',
    ]),
    `export const CANONICAL_UNITS = ${tsObject(canonical)} as const;`,
    '',
    `export const UNIT_SYSTEMS = ${tsArray(units.unitSystems)} as const;`,
    '',
    `export const MEASUREMENT_SOURCES = ${tsArray(units.measurementSources)} as const;`,
    '',
    ...Object.entries(units.conversionFactors).map(
      ([k, v]) => `export const ${upperSnake(k)} = ${String(v)};`,
    ),
    '',
  ].join('\n');
  return out;
}
