// shared-kernel registries -> Swift (target AIStylistKernel in packages/contracts/gen/swift-client).
// Every type is a String-backed enum (CaseIterable, Sendable) or a namespace enum of static lets,
// so the module compiles under Swift 6 strict concurrency with no dependencies.
import { camel, docText, num, pascal, src, stripRc, swiftIdent, swiftStr } from './naming.mjs';

const banner = (name) =>
  `// GENERATED by tools/codegen/gen-kernel.mjs from ${src(name)}. DO NOT EDIT: run \`just generate\`.\n`;

const swiftEnum = ({ doc, name, cases, props = [] }) => {
  const lines = [`/// ${docText(doc)}`, `public enum ${name}: String, CaseIterable, Sendable {`];
  for (const c of cases) {
    if (c.doc) lines.push(`  /// ${docText(c.doc)}`);
    lines.push(`  case ${swiftIdent(c.id)} = ${swiftStr(c.raw)}`);
  }
  for (const p of props) {
    lines.push(
      '',
      `  /// ${docText(p.doc)}`,
      `  public var ${p.name}: ${p.type} {`,
      '    switch self {',
    );
    for (const c of cases) lines.push(`    case .${swiftIdent(c.id)}: ${p.value(c)}`);
    lines.push('    }', '  }');
  }
  lines.push('}');
  return lines.join('\n');
};
const simpleCases = (values) => values.map((v) => ({ id: camel(v), raw: v }));
const describe = {
  doc: 'Human-readable meaning (registry text, not UI copy).',
  name: 'description',
  type: 'String',
  value: (c) => swiftStr(c.def.description),
};

export function emitSwift(reg) {
  const rc = reg['reason-codes'];
  const ent = reg.entitlements;
  const units = reg.units;
  const out = {};

  out['ReasonCodes.swift'] = [
    banner('reason-codes'),
    swiftEnum({
      doc: 'Reason-code namespace (planning/09 §7).',
      name: 'ReasonCodeNamespace',
      cases: rc.namespaces.map((n) => ({ id: camel(stripRc(n.name)), raw: n.name, doc: n.note })),
    }),
    '',
    swiftEnum({
      doc: 'Pipeline stage (planning/09 §2) that may emit a reason code.',
      name: 'ReasonCodeStage',
      cases: simpleCases(rc.stages),
    }),
    '',
    swiftEnum({
      doc: 'Recommendation reason code (planning/09 §7): a stable identifier emitted while deciding; explanations are templated from it.',
      name: 'ReasonCode',
      cases: Object.entries(rc.codes).map(([code, def]) => ({
        id: camel(stripRc(code)),
        raw: code,
        doc: def.description,
        def,
      })),
      props: [
        {
          doc: 'Namespace the code belongs to.',
          name: 'namespace',
          type: 'ReasonCodeNamespace',
          value: (c) => `.${swiftIdent(camel(stripRc(c.def.namespace)))}`,
        },
        {
          doc: 'Stage that may emit the code.',
          name: 'stage',
          type: 'ReasonCodeStage',
          value: (c) => `.${swiftIdent(camel(c.def.stage))}`,
        },
        {
          doc: 'Names of the typed template params (planning/09 §7).',
          name: 'params',
          type: '[String]',
          value: (c) => `[${c.def.params.map(swiftStr).join(', ')}]`,
        },
        describe,
      ],
    }),
    '',
  ].join('\n');

  out['Entitlements.swift'] = [
    banner('entitlements'),
    swiftEnum({
      doc: 'Value kind of an entitlement (planning/12 §3.1).',
      name: 'EntitlementValueKind',
      cases: simpleCases(ent.kinds),
    }),
    '',
    swiftEnum({
      doc: 'Entitlement name (planning/12 §3.1): the only entitlement identifiers.',
      name: 'EntitlementName',
      cases: Object.entries(ent.entitlements).map(([name, def]) => ({
        id: camel(name),
        raw: name,
        doc: def.description,
        def,
      })),
      props: [
        {
          doc: 'Value kind of the entitlement.',
          name: 'kind',
          type: 'EntitlementValueKind',
          value: (c) => `.${swiftIdent(camel(c.def.kind))}`,
        },
        describe,
      ],
    }),
    '',
    swiftEnum({
      doc: 'Weighted generative task metered against `credits.monthly` (planning/12 §3.3).',
      name: 'CreditMeter',
      cases: simpleCases(ent.creditMeters),
    }),
    '',
  ].join('\n');

  const dims = Object.entries(units.dimensions);
  out['Units.swift'] = [
    banner('units'),
    ...dims.flatMap(([d, def]) => [
      swiftEnum({
        doc: `Canonical ${d} unit(s) (planning/06 §2): the API stores and returns SI.`,
        name: `${pascal(d)}Unit`,
        cases: simpleCases(def.units),
      }),
      '',
    ]),
    swiftEnum({
      doc: 'Measurement dimension (TS `Dimension`; renamed to avoid Foundation.Dimension).',
      name: 'MeasurementDimension',
      cases: dims.map(([d, def]) => ({ id: camel(d), raw: d, def })),
      props: [
        {
          doc: 'Raw value of the canonical (stored) unit for this dimension.',
          name: 'canonicalUnit',
          type: 'String',
          value: (c) => swiftStr(c.def.canonical),
        },
      ],
    }),
    '',
    '/// Canonical (stored) unit per dimension.',
    'public enum CanonicalUnits {',
    ...dims.map(
      ([d, def]) =>
        `  public static let ${swiftIdent(camel(d))}: ${pascal(d)}Unit = .${swiftIdent(camel(def.canonical))}`,
    ),
    '}',
    '',
    swiftEnum({
      doc: 'Display unit system selectable in the profile (planning/06 §3.1 `locale.unitSystem`).',
      name: 'UnitSystem',
      cases: simpleCases(units.unitSystems),
    }),
    '',
    swiftEnum({
      doc: 'Who produced a measurement value (planning/06 §3.1): estimated/derived values must carry confidence.',
      name: 'MeasurementSource',
      cases: simpleCases(units.measurementSources),
    }),
    '',
    '/// Exact display-conversion factors (planning/06 §3.1); storage stays SI.',
    'public enum ConversionFactors {',
    ...Object.entries(units.conversionFactors).map(
      ([k, v]) => `  public static let ${swiftIdent(k)}: Double = ${num(v)}`,
    ),
    '}',
    '',
  ].join('\n');
  return out;
}
